[workspace]
members = [
    "ch01-hello-cargo",
    "ch02-guessing-games",
    "ch03-variables",
    "ch04-ownership",
    "ch05-structs",
    "ch06-enum-pattern-matching",
    "ch07-backyard",
]
resolver = "2"
